apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-deployment
  name: web-deployment
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - image: sameerahmedbalaganur/web-ecomm:v4
        imagePullPolicy: IfNotPresent
        name: web-ecomm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: DB_HOST
            value: mysql-service
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: DB_NAME
            value: ecomdb
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        
      # dnsPolicy: ClusterFirst
      # restartPolicy: Always
    