apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
          - containerPort: 3306
            # name: db-port
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: MYSQL_DATABASE
            value: "ecomdb"
          - name: MYSQL_ROOT_PASSWORD
            value: "my-secret-pw"
        volumeMounts:
          - name: mysql-pv-volume
            mountPath: /var/lib/mysql
          - name: mysql-init-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init-script
          configMap:
            name: db-load-script.sql
        - name: mysql-pv-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
    